### ISSUE TITLE
Correction nécessaire dans la définition des invariants

### ISSUE THREAD

**Issue by seuadk** [ansforge/IG-fhir-partage-de-documents-de-sante#62]
Bonjour, 

Je tiens à attirer votre attention sur une erreur identifiée dans la définition des invariants . Il me semble que la distinction entre l'élément "Expression" et l'élément "XPath" n'a pas été correctement établie dans vos spécifications.

Il est crucial de noter que ces deux éléments diffèrent fondamentalement dans leur utilisation et leur contexte d'application. L'erreur dans la classification de ces éléments risque de causer des ambiguïtés dans l'interprétation et l'application des invariants.

Liens utiles :
-  https://www.hl7.org/fhir/uv/shorthand/2020May/reference.html#defining-invariants 
-  https://www.hl7.org/fhir/R4/conformance-rules.html#constraints

Respectueusement,  

Seuad Kassa

**Comment by nriss** [comment]
Merci pour l'issue! Je la close, car l'issue est déjà ouverte à ce sujet : https://github.com/ansforge/IG-fhir-partage-de-documents-de-sante/issues/23

Il va effectivement falloir que l'on corrige ça.
