### ISSUE TITLE
Page de téléchargement du package en 404

### ISSUE THREAD

**Issue by 3abdel3ali** [ansforge/IG-fhir-partage-de-documents-de-sante#65]
impossible de télécharger le package en question 

![image](https://github.com/ansforge/IG-fhir-partage-de-documents-de-sante/assets/26487232/8967db0f-a9bc-47dc-a661-b4743ac8eb4d)

**Comment by nriss** [comment]
Hello! 
C'est le comportement attendu, Mael a désactivé la possibilité de télécharger sur la version en intégration continue pour éviter l'implémentation d'une version qui n'est pas stabilisée.
Le téléchargement fonctionne uniquement sur l'url canonique, sur les versions publiées.

Ex. ici : https://interop.esante.gouv.fr/ig/fhir/pdsm/downloads.html
